# Generated by Django 5.0.2 on 2024-02-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app2', '0001_migrate1'), ('app2', '0002_migrate2')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('nw', 'Новая'), ('nn', 'Б/У')], default='nw', max_length=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.brand')),
                ('price', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
            ],
        ),
    ]
