# Generated by Django 5.0.2 on 2024-02-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_migrate1'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='models',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
