# Generated by Django 5.0.2 on 2024-02-26 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_migrate1'), ('app', '0003_migrate2')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('age', models.ImageField(upload_to='')),
                ('work', models.CharField(max_length=255)),
                ('status', models.CharField(default='None', max_length=255)),
                ('post', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
    ]
