# Generated by Django 5.0.2 on 2024-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
