# Generated by Django 5.0.2 on 2024-02-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_migrate2'),
    ]

    operations = [
    ]
