# Generated by Django 5.0.2 on 2024-02-26 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240226_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
